export const CREATE_PARTICIPANT = 'CREATE_PARTICIPANT';
export const FETCH_PARTICIPANTS = 'FETCH_PARTICIPANTS';
export const FETCH_PARTICIPANT = 'FETCH_PARTICIPANT';
export const DELETE_PARTICIPANT = 'DELETE_PARTICIPANT';
export const EDIT_PARTICIPANT = 'EDIT_PARTICIPANT';
