export const REVIEWED_STATUS_NOT_REVIEWED = 'NOT REVIEWED';
export const REVIEWED_STATUS_REVIEWED_ACCEPTED = 'REVIEW ACCEPTED'
export const REVIEWED_STATUS_REVIEWED_NOT_ACCEPTED = 'REVIEW NOT ACCEPTED'
